import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="flex-col flex justify-between items-center py-1" >
            <h4>Welcome to Bosunaire</h4>
            <h6>Yoyo with Bo</h6>
        </div>
    </>
  )
}
